[2023-12-10T18:06:24.947+0000] {processor.py:157} INFO - Started process (PID=30) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:06:24.956+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:06:24.965+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:06:24.965+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:06:25.055+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:06:25.049+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 4, in <module>
    from data import create_tables
ModuleNotFoundError: No module named 'data'
[2023-12-10T18:06:25.064+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:06:25.107+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.171 seconds
[2023-12-10T18:06:55.477+0000] {processor.py:157} INFO - Started process (PID=85) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:06:55.480+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:06:55.486+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:06:55.486+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:06:55.529+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:06:55.525+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 4, in <module>
    from data import create_tables
ModuleNotFoundError: No module named 'data'
[2023-12-10T18:06:55.530+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:06:55.575+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.111 seconds
[2023-12-10T18:07:25.749+0000] {processor.py:157} INFO - Started process (PID=140) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:07:25.752+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:07:25.757+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:07:25.757+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:07:25.771+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:07:25.769+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 4, in <module>
    from data import create_tables
ModuleNotFoundError: No module named 'data'
[2023-12-10T18:07:25.772+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:07:25.805+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.065 seconds
[2023-12-10T18:07:55.958+0000] {processor.py:157} INFO - Started process (PID=195) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:07:55.959+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:07:55.963+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:07:55.963+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:07:55.973+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:07:55.972+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 4, in <module>
    from data import create_tables
ModuleNotFoundError: No module named 'data'
[2023-12-10T18:07:55.974+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:07:55.995+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.042 seconds
[2023-12-10T18:09:39.986+0000] {processor.py:157} INFO - Started process (PID=31) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:09:40.002+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:09:40.049+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:09:40.048+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:09:40.082+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:09:40.078+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 4, in <module>
    from data import create_tables
ModuleNotFoundError: No module named 'data'
[2023-12-10T18:09:40.087+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:09:40.151+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.220 seconds
[2023-12-10T18:10:10.396+0000] {processor.py:157} INFO - Started process (PID=39) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:10:10.398+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:10:10.403+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:10:10.402+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:10:10.412+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:10:10.411+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 4, in <module>
    from data import create_tables
ModuleNotFoundError: No module named 'data'
[2023-12-10T18:10:10.414+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:10:10.445+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.055 seconds
[2023-12-10T18:10:40.662+0000] {processor.py:157} INFO - Started process (PID=47) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:10:40.663+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:10:40.666+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:10:40.666+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:10:40.675+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:10:40.673+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 4, in <module>
    from data import create_tables
ModuleNotFoundError: No module named 'data'
[2023-12-10T18:10:40.676+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:10:40.703+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.045 seconds
[2023-12-10T18:11:10.889+0000] {processor.py:157} INFO - Started process (PID=55) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:11:10.891+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:11:10.894+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:11:10.894+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:11:10.901+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:11:10.900+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 4, in <module>
    from data import create_tables
ModuleNotFoundError: No module named 'data'
[2023-12-10T18:11:10.902+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:11:10.927+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.042 seconds
[2023-12-10T18:11:41.286+0000] {processor.py:157} INFO - Started process (PID=63) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:11:41.288+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:11:41.312+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:11:41.312+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:11:41.343+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:11:41.340+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 4, in <module>
    from data import create_tables
ModuleNotFoundError: No module named 'data'
[2023-12-10T18:11:41.344+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:11:41.377+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.097 seconds
[2023-12-10T18:12:11.496+0000] {processor.py:157} INFO - Started process (PID=71) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:12:11.498+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:12:11.502+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:12:11.501+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:12:11.517+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:12:11.513+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 4, in <module>
    from data import create_tables
ModuleNotFoundError: No module named 'data'
[2023-12-10T18:12:11.518+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:12:11.553+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.063 seconds
[2023-12-10T18:12:41.773+0000] {processor.py:157} INFO - Started process (PID=79) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:12:41.775+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:12:41.778+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:12:41.778+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:12:41.788+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:12:41.786+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 4, in <module>
    from data import create_tables
ModuleNotFoundError: No module named 'data'
[2023-12-10T18:12:41.790+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:12:41.823+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.053 seconds
[2023-12-10T18:13:12.012+0000] {processor.py:157} INFO - Started process (PID=87) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:13:12.014+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:13:12.019+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:13:12.018+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:13:12.039+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:13:12.036+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 4, in <module>
    from data import create_tables
ModuleNotFoundError: No module named 'data'
[2023-12-10T18:13:12.040+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:13:12.074+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.067 seconds
[2023-12-10T18:13:42.226+0000] {processor.py:157} INFO - Started process (PID=95) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:13:42.227+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:13:42.232+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:13:42.231+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:13:42.244+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:13:42.242+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 4, in <module>
    from data import create_tables
ModuleNotFoundError: No module named 'data'
[2023-12-10T18:13:42.246+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:13:42.274+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.052 seconds
[2023-12-10T18:13:53.374+0000] {processor.py:157} INFO - Started process (PID=103) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:13:53.376+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:13:53.380+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:13:53.379+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:13:53.387+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:13:53.386+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 4
    from data import connection,
                     ^
SyntaxError: trailing comma not allowed without surrounding parentheses
[2023-12-10T18:13:53.388+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:13:53.410+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.041 seconds
[2023-12-10T18:13:55.404+0000] {processor.py:157} INFO - Started process (PID=104) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:13:55.406+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:13:55.409+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:13:55.408+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:13:55.424+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:13:55.421+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 4, in <module>
    from data import connection, hello
ModuleNotFoundError: No module named 'data'
[2023-12-10T18:13:55.427+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:13:55.456+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.058 seconds
[2023-12-10T18:13:56.627+0000] {processor.py:157} INFO - Started process (PID=105) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:13:56.630+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:13:56.635+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:13:56.634+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:13:56.661+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:13:56.659+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 4, in <module>
    from data import connection, hello_
ModuleNotFoundError: No module named 'data'
[2023-12-10T18:13:56.664+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:13:56.690+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.068 seconds
[2023-12-10T18:13:58.662+0000] {processor.py:157} INFO - Started process (PID=106) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:13:58.664+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:13:58.668+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:13:58.667+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:13:58.763+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:13:58.761+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 4, in <module>
    from data import connection, hello_test
ModuleNotFoundError: No module named 'data'
[2023-12-10T18:13:58.765+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:13:58.790+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.133 seconds
[2023-12-10T18:14:05.879+0000] {processor.py:157} INFO - Started process (PID=107) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:14:05.894+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:14:05.903+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:14:05.902+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:14:05.935+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:14:05.933+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 4, in <module>
    from data import connection, hello_test
ModuleNotFoundError: No module named 'data'
[2023-12-10T18:14:05.936+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:14:05.974+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.103 seconds
[2023-12-10T18:14:07.959+0000] {processor.py:157} INFO - Started process (PID=108) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:14:07.961+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:14:07.966+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:14:07.966+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:14:08.030+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:14:08.027+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 4, in <module>
    from data import connection, hello_test
ModuleNotFoundError: No module named 'data'
[2023-12-10T18:14:08.033+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:14:08.061+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.110 seconds
[2023-12-10T18:14:10.036+0000] {processor.py:157} INFO - Started process (PID=109) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:14:10.038+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:14:10.042+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:14:10.042+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:14:10.064+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:14:10.062+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 4, in <module>
    from data import connection, hello_test
ModuleNotFoundError: No module named 'data'
[2023-12-10T18:14:10.066+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:14:10.104+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.073 seconds
[2023-12-10T18:14:15.151+0000] {processor.py:157} INFO - Started process (PID=110) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:14:15.152+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:14:15.156+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:14:15.155+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:14:15.224+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:14:15.221+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 4, in <module>
    from data import connection, hello_test
ModuleNotFoundError: No module named 'data'
[2023-12-10T18:14:15.226+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:14:15.248+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.103 seconds
[2023-12-10T18:14:21.321+0000] {processor.py:157} INFO - Started process (PID=118) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:14:21.323+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:14:21.327+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:14:21.327+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:14:21.440+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:14:21.436+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 4, in <module>
    from data import connection, hello_test
ModuleNotFoundError: No module named 'data'
[2023-12-10T18:14:21.442+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:14:21.479+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.162 seconds
[2023-12-10T18:14:25.372+0000] {processor.py:157} INFO - Started process (PID=119) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:14:25.374+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:14:25.377+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:14:25.376+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:14:25.395+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:14:25.393+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 4, in <module>
    from data import connection, hello_test
ModuleNotFoundError: No module named 'data'
[2023-12-10T18:14:25.397+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:14:25.422+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.054 seconds
[2023-12-10T18:14:30.427+0000] {processor.py:157} INFO - Started process (PID=120) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:14:30.429+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:14:30.432+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:14:30.432+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:14:30.449+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:14:30.447+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 4, in <module>
    from data import connection, hello_test
ModuleNotFoundError: No module named 'data'
[2023-12-10T18:14:30.450+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:14:30.475+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.052 seconds
[2023-12-10T18:14:37.538+0000] {processor.py:157} INFO - Started process (PID=121) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:14:37.540+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:14:37.542+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:14:37.542+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:14:37.554+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:14:37.553+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 20
    2 = PythonOperator(
    ^
SyntaxError: cannot assign to literal
[2023-12-10T18:14:37.555+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:14:37.577+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.043 seconds
[2023-12-10T18:14:41.635+0000] {processor.py:157} INFO - Started process (PID=122) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:14:41.636+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:14:41.640+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:14:41.639+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:14:41.652+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:14:41.650+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 4, in <module>
    from data import connection, hello_test
ModuleNotFoundError: No module named 'data'
[2023-12-10T18:14:41.653+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:14:41.679+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.048 seconds
[2023-12-10T18:14:45.685+0000] {processor.py:157} INFO - Started process (PID=123) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:14:45.686+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:14:45.690+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:14:45.690+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:14:45.707+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:14:45.705+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 4, in <module>
    from data import connection, hello_test
ModuleNotFoundError: No module named 'data'
[2023-12-10T18:14:45.709+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:14:45.735+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.054 seconds
[2023-12-10T18:14:47.743+0000] {processor.py:157} INFO - Started process (PID=124) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:14:47.745+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:14:47.753+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:14:47.752+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:14:47.769+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:14:47.767+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 4, in <module>
    from data import connection, hello_test
ModuleNotFoundError: No module named 'data'
[2023-12-10T18:14:47.770+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:14:47.792+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.054 seconds
[2023-12-10T18:14:54.891+0000] {processor.py:157} INFO - Started process (PID=132) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:14:54.893+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:14:54.898+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:14:54.897+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:14:54.918+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:14:54.916+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 4, in <module>
    from data import connection, hello_test
ModuleNotFoundError: No module named 'data'
[2023-12-10T18:14:54.919+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:14:54.940+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.055 seconds
[2023-12-10T18:14:55.917+0000] {processor.py:157} INFO - Started process (PID=133) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:14:55.919+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:14:55.922+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:14:55.922+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:14:55.982+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:14:55.980+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 4, in <module>
    from data import connection, hello_test
ModuleNotFoundError: No module named 'data'
[2023-12-10T18:14:55.983+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:14:56.019+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.106 seconds
[2023-12-10T18:15:03.033+0000] {processor.py:157} INFO - Started process (PID=134) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:15:03.034+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:15:03.039+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:15:03.038+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:15:03.085+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:15:03.081+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 4, in <module>
    from data import connection, hello_test
ModuleNotFoundError: No module named 'data'
[2023-12-10T18:15:03.087+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:15:03.120+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.092 seconds
[2023-12-10T18:15:33.300+0000] {processor.py:157} INFO - Started process (PID=142) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:15:33.302+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:15:33.306+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:15:33.305+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:15:33.321+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:15:33.319+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 4, in <module>
    from data import connection, hello_test
ModuleNotFoundError: No module named 'data'
[2023-12-10T18:15:33.337+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:15:33.364+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.070 seconds
[2023-12-10T18:15:44.492+0000] {processor.py:157} INFO - Started process (PID=143) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:15:44.493+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:15:44.497+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:15:44.497+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:15:44.510+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:15:44.508+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 4, in <module>
    from data.create_tables import connection, hello_test
ModuleNotFoundError: No module named 'data'
[2023-12-10T18:15:44.511+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:15:44.537+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.050 seconds
[2023-12-10T18:15:50.592+0000] {processor.py:157} INFO - Started process (PID=151) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:15:50.593+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:15:50.596+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:15:50.596+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:15:50.614+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:15:50.612+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 4, in <module>
    from data.create_tables import connection, hello_test
ModuleNotFoundError: No module named 'data'
[2023-12-10T18:15:50.615+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:15:50.646+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.059 seconds
[2023-12-10T18:16:20.851+0000] {processor.py:157} INFO - Started process (PID=159) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:16:20.852+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:16:20.856+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:16:20.855+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:16:20.923+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:16:20.921+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 4, in <module>
    from data.create_tables import connection, hello_test
ModuleNotFoundError: No module named 'data'
[2023-12-10T18:16:20.925+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:16:20.951+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.104 seconds
[2023-12-10T18:16:51.073+0000] {processor.py:157} INFO - Started process (PID=167) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:16:51.074+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:16:51.078+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:16:51.078+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:16:51.087+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:16:51.085+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 4, in <module>
    from data.create_tables import connection, hello_test
ModuleNotFoundError: No module named 'data'
[2023-12-10T18:16:51.088+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:16:51.113+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.044 seconds
[2023-12-10T18:17:21.375+0000] {processor.py:157} INFO - Started process (PID=175) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:17:21.376+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:17:21.379+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:17:21.379+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:17:21.390+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:17:21.388+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 4, in <module>
    from data.create_tables import connection, hello_test
ModuleNotFoundError: No module named 'data'
[2023-12-10T18:17:21.391+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:17:21.415+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.045 seconds
[2023-12-10T18:17:51.586+0000] {processor.py:157} INFO - Started process (PID=183) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:17:51.588+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:17:51.591+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:17:51.591+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:17:51.603+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:17:51.601+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 4, in <module>
    from data.create_tables import connection, hello_test
ModuleNotFoundError: No module named 'data'
[2023-12-10T18:17:51.604+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:17:51.632+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.051 seconds
[2023-12-10T18:27:11.549+0000] {processor.py:157} INFO - Started process (PID=31) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:27:11.550+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:27:11.553+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:27:11.552+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:27:11.590+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:27:11.588+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 4, in <module>
    from data.create_tables import connection, hello_test
ModuleNotFoundError: No module named 'data'
[2023-12-10T18:27:11.591+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:27:11.623+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.081 seconds
[2023-12-10T18:27:41.867+0000] {processor.py:157} INFO - Started process (PID=39) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:27:41.870+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:27:41.875+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:27:41.875+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:27:41.891+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:27:41.889+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 4, in <module>
    from data.create_tables import connection, hello_test
ModuleNotFoundError: No module named 'data'
[2023-12-10T18:27:41.893+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:27:41.913+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.054 seconds
[2023-12-10T18:28:12.142+0000] {processor.py:157} INFO - Started process (PID=47) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:28:12.143+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:28:12.147+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:28:12.146+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:28:12.158+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:28:12.155+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 4, in <module>
    from data.create_tables import connection, hello_test
ModuleNotFoundError: No module named 'data'
[2023-12-10T18:28:12.159+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:28:12.183+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.045 seconds
[2023-12-10T18:28:42.486+0000] {processor.py:157} INFO - Started process (PID=55) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:28:42.487+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:28:42.491+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:28:42.491+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:28:42.502+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:28:42.500+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 4, in <module>
    from data.create_tables import connection, hello_test
ModuleNotFoundError: No module named 'data'
[2023-12-10T18:28:42.503+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:28:42.523+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.041 seconds
[2023-12-10T18:29:12.804+0000] {processor.py:157} INFO - Started process (PID=63) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:29:12.807+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:29:12.811+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:29:12.810+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:29:12.820+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:29:12.818+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 4, in <module>
    from data.create_tables import connection, hello_test
ModuleNotFoundError: No module named 'data'
[2023-12-10T18:29:12.821+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:29:12.843+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.046 seconds
[2023-12-10T18:29:43.062+0000] {processor.py:157} INFO - Started process (PID=71) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:29:43.064+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:29:43.069+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:29:43.069+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:29:43.081+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:29:43.079+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 4, in <module>
    from data.create_tables import connection, hello_test
ModuleNotFoundError: No module named 'data'
[2023-12-10T18:29:43.082+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:29:43.109+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.055 seconds
[2023-12-10T18:30:13.476+0000] {processor.py:157} INFO - Started process (PID=79) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:30:13.479+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:30:13.504+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:30:13.503+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:30:13.538+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:30:13.536+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 4, in <module>
    from data.create_tables import connection, hello_test
ModuleNotFoundError: No module named 'data'
[2023-12-10T18:30:13.549+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:30:13.598+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.131 seconds
[2023-12-10T18:30:43.778+0000] {processor.py:157} INFO - Started process (PID=87) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:30:43.779+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:30:43.784+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:30:43.783+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:30:43.794+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:30:43.792+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 4, in <module>
    from data.create_tables import connection, hello_test
ModuleNotFoundError: No module named 'data'
[2023-12-10T18:30:43.795+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:30:43.822+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.050 seconds
[2023-12-10T18:31:14.101+0000] {processor.py:157} INFO - Started process (PID=95) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:31:14.103+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:31:14.107+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:31:14.106+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:31:14.117+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:31:14.115+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 4, in <module>
    from data.create_tables import connection, hello_test
ModuleNotFoundError: No module named 'data'
[2023-12-10T18:31:14.118+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:31:14.148+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.052 seconds
[2023-12-10T18:31:44.420+0000] {processor.py:157} INFO - Started process (PID=103) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:31:44.422+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:31:44.428+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:31:44.427+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:31:44.439+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:31:44.436+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 4, in <module>
    from data.create_tables import connection, hello_test
ModuleNotFoundError: No module named 'data'
[2023-12-10T18:31:44.440+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:31:44.471+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.060 seconds
[2023-12-10T18:32:14.759+0000] {processor.py:157} INFO - Started process (PID=111) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:32:14.760+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:32:14.764+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:32:14.763+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:32:14.773+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:32:14.771+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 4, in <module>
    from data.create_tables import connection, hello_test
ModuleNotFoundError: No module named 'data'
[2023-12-10T18:32:14.774+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:32:14.796+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.042 seconds
[2023-12-10T18:32:45.063+0000] {processor.py:157} INFO - Started process (PID=119) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:32:45.065+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:32:45.068+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:32:45.068+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:32:45.076+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:32:45.074+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 4, in <module>
    from data.create_tables import connection, hello_test
ModuleNotFoundError: No module named 'data'
[2023-12-10T18:32:45.077+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:32:45.101+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.042 seconds
[2023-12-10T18:33:15.348+0000] {processor.py:157} INFO - Started process (PID=127) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:33:15.350+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:33:15.353+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:33:15.353+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:33:15.363+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:33:15.361+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 4, in <module>
    from data.create_tables import connection, hello_test
ModuleNotFoundError: No module named 'data'
[2023-12-10T18:33:15.364+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:33:15.387+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.043 seconds
[2023-12-10T18:33:45.629+0000] {processor.py:157} INFO - Started process (PID=135) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:33:45.631+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:33:45.634+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:33:45.633+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:33:45.646+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:33:45.644+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 4, in <module>
    from data.create_tables import connection, hello_test
ModuleNotFoundError: No module named 'data'
[2023-12-10T18:33:45.647+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:33:45.674+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.049 seconds
[2023-12-10T18:34:16.012+0000] {processor.py:157} INFO - Started process (PID=143) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:34:16.014+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:34:16.020+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:34:16.020+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:34:16.033+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:34:16.031+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 4, in <module>
    from data.create_tables import connection, hello_test
ModuleNotFoundError: No module named 'data'
[2023-12-10T18:34:16.034+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:34:16.064+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.062 seconds
[2023-12-10T18:34:46.331+0000] {processor.py:157} INFO - Started process (PID=151) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:34:46.333+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:34:46.338+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:34:46.337+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:34:46.349+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:34:46.347+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 4, in <module>
    from data.create_tables import connection, hello_test
ModuleNotFoundError: No module named 'data'
[2023-12-10T18:34:46.350+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:34:46.372+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.050 seconds
[2023-12-10T18:35:16.597+0000] {processor.py:157} INFO - Started process (PID=159) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:35:16.599+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:35:16.603+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:35:16.602+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:35:16.612+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:35:16.610+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 4, in <module>
    from data.create_tables import connection, hello_test
ModuleNotFoundError: No module named 'data'
[2023-12-10T18:35:16.613+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:35:16.634+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.041 seconds
[2023-12-10T18:35:46.918+0000] {processor.py:157} INFO - Started process (PID=167) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:35:46.920+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:35:46.925+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:35:46.925+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:35:46.936+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:35:46.933+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 4, in <module>
    from data.create_tables import connection, hello_test
ModuleNotFoundError: No module named 'data'
[2023-12-10T18:35:46.937+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:35:46.966+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.052 seconds
[2023-12-10T18:36:17.167+0000] {processor.py:157} INFO - Started process (PID=175) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:36:17.168+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:36:17.172+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:36:17.171+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:36:17.183+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:36:17.180+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 4, in <module>
    from data.create_tables import connection, hello_test
ModuleNotFoundError: No module named 'data'
[2023-12-10T18:36:17.184+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:36:17.211+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.048 seconds
[2023-12-10T18:36:47.485+0000] {processor.py:157} INFO - Started process (PID=183) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:36:47.487+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:36:47.491+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:36:47.490+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:36:47.501+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:36:47.499+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 4, in <module>
    from data.create_tables import connection, hello_test
ModuleNotFoundError: No module named 'data'
[2023-12-10T18:36:47.502+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:36:47.522+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.042 seconds
[2023-12-10T18:37:17.774+0000] {processor.py:157} INFO - Started process (PID=191) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:37:17.775+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:37:17.779+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:37:17.778+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:37:17.789+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:37:17.786+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 4, in <module>
    from data.create_tables import connection, hello_test
ModuleNotFoundError: No module named 'data'
[2023-12-10T18:37:17.790+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:37:17.814+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.043 seconds
[2023-12-10T18:37:48.086+0000] {processor.py:157} INFO - Started process (PID=199) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:37:48.087+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:37:48.091+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:37:48.091+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:37:48.103+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:37:48.101+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 4, in <module>
    from data.create_tables import connection, hello_test
ModuleNotFoundError: No module named 'data'
[2023-12-10T18:37:48.104+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:37:48.126+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.045 seconds
[2023-12-10T18:38:18.440+0000] {processor.py:157} INFO - Started process (PID=207) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:38:18.443+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:38:18.448+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:38:18.448+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:38:18.460+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:38:18.458+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 4, in <module>
    from data.create_tables import connection, hello_test
ModuleNotFoundError: No module named 'data'
[2023-12-10T18:38:18.461+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:38:18.486+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.054 seconds
[2023-12-10T18:38:48.745+0000] {processor.py:157} INFO - Started process (PID=215) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:38:48.746+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:38:48.749+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:38:48.749+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:38:48.758+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:38:48.757+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 4, in <module>
    from data.create_tables import connection, hello_test
ModuleNotFoundError: No module named 'data'
[2023-12-10T18:38:48.759+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:38:48.783+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.042 seconds
[2023-12-10T18:41:30.805+0000] {processor.py:157} INFO - Started process (PID=30) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:41:30.811+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:41:30.816+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:41:30.816+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:41:30.829+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:41:30.826+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 4, in <module>
    from data.create_tables import connection, hello_test
ModuleNotFoundError: No module named 'data'
[2023-12-10T18:41:30.831+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:41:30.872+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.075 seconds
[2023-12-10T18:42:01.073+0000] {processor.py:157} INFO - Started process (PID=38) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:42:01.075+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:42:01.078+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:42:01.078+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:42:01.091+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:42:01.089+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 4, in <module>
    from data.create_tables import connection, hello_test
ModuleNotFoundError: No module named 'data'
[2023-12-10T18:42:01.092+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:42:01.121+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.052 seconds
[2023-12-10T18:42:31.301+0000] {processor.py:157} INFO - Started process (PID=46) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:42:31.302+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:42:31.305+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:42:31.305+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:42:31.314+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:42:31.312+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 4, in <module>
    from data.create_tables import connection, hello_test
ModuleNotFoundError: No module named 'data'
[2023-12-10T18:42:31.316+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:42:31.339+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.043 seconds
[2023-12-10T18:43:01.569+0000] {processor.py:157} INFO - Started process (PID=54) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:43:01.571+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:43:01.576+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:43:01.576+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:43:01.592+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:43:01.589+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 4, in <module>
    from data.create_tables import connection, hello_test
ModuleNotFoundError: No module named 'data'
[2023-12-10T18:43:01.594+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:43:01.632+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.068 seconds
[2023-12-10T18:43:31.839+0000] {processor.py:157} INFO - Started process (PID=62) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:43:31.840+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:43:31.844+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:43:31.843+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:43:31.853+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:43:31.851+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 4, in <module>
    from data.create_tables import connection, hello_test
ModuleNotFoundError: No module named 'data'
[2023-12-10T18:43:31.854+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:43:31.877+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.043 seconds
[2023-12-10T18:44:00.072+0000] {processor.py:157} INFO - Started process (PID=70) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:44:00.073+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:44:00.076+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:44:00.076+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:44:00.135+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:44:00.132+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 4, in <module>
    from create_tables import connection, hello_test
ModuleNotFoundError: No module named 'create_tables'
[2023-12-10T18:44:00.137+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:44:00.167+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.099 seconds
[2023-12-10T18:44:30.379+0000] {processor.py:157} INFO - Started process (PID=78) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:44:30.380+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:44:30.383+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:44:30.383+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:44:30.439+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:44:30.433+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 4, in <module>
    from create_tables import connection, hello_test
ModuleNotFoundError: No module named 'create_tables'
[2023-12-10T18:44:30.440+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:44:30.475+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.102 seconds
[2023-12-10T18:45:00.719+0000] {processor.py:157} INFO - Started process (PID=85) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:45:00.725+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:45:00.742+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:45:00.741+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:45:00.754+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:45:00.751+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 4, in <module>
    from create_tables import connection, hello_test
ModuleNotFoundError: No module named 'create_tables'
[2023-12-10T18:45:00.756+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:45:00.793+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.080 seconds
[2023-12-10T18:45:30.967+0000] {processor.py:157} INFO - Started process (PID=93) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:45:30.971+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:45:30.978+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:45:30.978+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:45:30.993+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:45:30.990+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 4, in <module>
    from create_tables import connection, hello_test
ModuleNotFoundError: No module named 'create_tables'
[2023-12-10T18:45:30.995+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:45:31.030+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.070 seconds
[2023-12-10T18:46:01.279+0000] {processor.py:157} INFO - Started process (PID=101) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:46:01.281+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:46:01.285+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:46:01.284+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:46:01.296+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:46:01.294+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 4, in <module>
    from create_tables import connection, hello_test
ModuleNotFoundError: No module named 'create_tables'
[2023-12-10T18:46:01.298+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:46:01.331+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.056 seconds
[2023-12-10T18:46:04.346+0000] {processor.py:157} INFO - Started process (PID=102) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:46:04.348+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:46:04.353+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:46:04.352+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:46:04.364+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:46:04.362+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 6
    import
          ^
SyntaxError: invalid syntax
[2023-12-10T18:46:04.365+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:46:04.396+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.057 seconds
[2023-12-10T18:46:07.447+0000] {processor.py:157} INFO - Started process (PID=103) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:46:07.448+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:46:07.451+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:46:07.451+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:46:07.465+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:46:07.463+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 7, in <module>
    from create_tables import connection, hello_test
ModuleNotFoundError: No module named 'create_tables'
[2023-12-10T18:46:07.467+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:46:07.553+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.112 seconds
[2023-12-10T18:46:08.540+0000] {processor.py:157} INFO - Started process (PID=104) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:46:08.542+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:46:08.551+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:46:08.550+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:46:08.610+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:46:08.608+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 7, in <module>
    from create_tables import connection, hello_test
ModuleNotFoundError: No module named 'create_tables'
[2023-12-10T18:46:08.612+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:46:08.674+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.138 seconds
[2023-12-10T18:46:09.642+0000] {processor.py:157} INFO - Started process (PID=105) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:46:09.643+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:46:09.647+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:46:09.647+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:46:09.663+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:46:09.661+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 8, in <module>
    from create_tables import connection, hello_test
ModuleNotFoundError: No module named 'create_tables'
[2023-12-10T18:46:09.664+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:46:09.691+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.053 seconds
[2023-12-10T18:46:13.767+0000] {processor.py:157} INFO - Started process (PID=106) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:46:13.768+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:46:13.771+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:46:13.771+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:46:13.891+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:46:13.889+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 7, in <module>
    path
NameError: name 'path' is not defined
[2023-12-10T18:46:13.893+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:46:13.921+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.158 seconds
[2023-12-10T18:46:14.845+0000] {processor.py:157} INFO - Started process (PID=107) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:46:14.846+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:46:14.850+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:46:14.849+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:46:14.914+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:46:14.912+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 7, in <module>
    path
NameError: name 'path' is not defined
[2023-12-10T18:46:14.915+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:46:14.948+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.107 seconds
[2023-12-10T18:46:17.032+0000] {processor.py:157} INFO - Started process (PID=108) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:46:17.035+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:46:17.039+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:46:17.039+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:46:17.056+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:46:17.054+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 8, in <module>
    from create_tables import connection, hello_test
ModuleNotFoundError: No module named 'create_tables'
[2023-12-10T18:46:17.057+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:46:17.085+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.060 seconds
[2023-12-10T18:46:19.074+0000] {processor.py:157} INFO - Started process (PID=109) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:46:19.076+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:46:19.079+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:46:19.079+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:46:19.240+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:46:19.237+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 8, in <module>
    from create_tables import connection, hello_test
ModuleNotFoundError: No module named 'create_tables'
[2023-12-10T18:46:19.242+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:46:19.269+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.200 seconds
[2023-12-10T18:46:23.215+0000] {processor.py:157} INFO - Started process (PID=117) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:46:23.218+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:46:23.222+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:46:23.222+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:46:23.293+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:46:23.290+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 11, in <module>
    from create_tables import connection, hello_test
ModuleNotFoundError: No module named 'create_tables'
[2023-12-10T18:46:23.295+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:46:23.325+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.120 seconds
[2023-12-10T18:46:28.401+0000] {processor.py:157} INFO - Started process (PID=118) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:46:28.402+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:46:28.405+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:46:28.404+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:46:28.554+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:46:28.549+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 11, in <module>
    from create_tables import connection, hello_test
ModuleNotFoundError: No module named 'create_tables'
[2023-12-10T18:46:28.556+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:46:28.584+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.186 seconds
[2023-12-10T18:46:29.480+0000] {processor.py:157} INFO - Started process (PID=119) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:46:29.481+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:46:29.485+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:46:29.485+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:46:29.498+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:46:29.497+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 8
    sys.
       ^
SyntaxError: invalid syntax
[2023-12-10T18:46:29.499+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:46:29.522+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.046 seconds
[2023-12-10T18:46:31.519+0000] {processor.py:157} INFO - Started process (PID=120) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:46:31.521+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:46:31.524+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:46:31.524+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:46:31.624+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:46:31.620+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 11, in <module>
    from create_tables import connection, hello_test
ModuleNotFoundError: No module named 'create_tables'
[2023-12-10T18:46:31.627+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:46:31.664+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.152 seconds
[2023-12-10T18:46:32.580+0000] {processor.py:157} INFO - Started process (PID=121) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:46:32.582+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:46:32.586+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:46:32.586+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:46:32.596+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:46:32.595+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 8
    sys.path.
            ^
SyntaxError: invalid syntax
[2023-12-10T18:46:32.597+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:46:32.617+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.041 seconds
[2023-12-10T18:46:38.705+0000] {processor.py:157} INFO - Started process (PID=122) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:46:38.706+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:46:38.711+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:46:38.711+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:46:38.724+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:46:38.723+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 11, in <module>
    from create_tables import connection, hello_test
ModuleNotFoundError: No module named 'create_tables'
[2023-12-10T18:46:38.725+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:46:38.749+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.049 seconds
[2023-12-10T18:46:39.747+0000] {processor.py:157} INFO - Started process (PID=123) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:46:39.748+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:46:39.753+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:46:39.753+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:46:39.775+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:46:39.772+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 8, in <module>
    sys.path.append()
TypeError: append() takes exactly one argument (0 given)
[2023-12-10T18:46:39.777+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:46:39.808+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.066 seconds
[2023-12-10T18:46:41.853+0000] {processor.py:157} INFO - Started process (PID=124) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:46:41.856+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:46:41.860+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:46:41.860+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:46:41.932+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:46:41.930+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 11, in <module>
    from create_tables import connection, hello_test
ModuleNotFoundError: No module named 'create_tables'
[2023-12-10T18:46:41.933+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:46:41.966+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.118 seconds
[2023-12-10T18:47:03.159+0000] {processor.py:157} INFO - Started process (PID=131) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:47:03.161+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:47:03.164+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:47:03.163+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:47:03.174+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:47:03.173+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 11
    import
          ^
SyntaxError: invalid syntax
[2023-12-10T18:47:03.175+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:47:03.204+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.049 seconds
[2023-12-10T18:47:08.208+0000] {processor.py:157} INFO - Started process (PID=132) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:47:08.209+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:47:08.213+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:47:08.212+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:47:08.226+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:47:08.224+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 11, in <module>
    import create
ModuleNotFoundError: No module named 'create'
[2023-12-10T18:47:08.227+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:47:08.252+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.048 seconds
[2023-12-10T18:47:11.343+0000] {processor.py:157} INFO - Started process (PID=133) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:47:11.345+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:47:11.347+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:47:11.347+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:47:11.364+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:47:11.363+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 11, in <module>
    import create_tables
ModuleNotFoundError: No module named 'create_tables'
[2023-12-10T18:47:11.365+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:47:11.387+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.048 seconds
[2023-12-10T18:47:41.619+0000] {processor.py:157} INFO - Started process (PID=140) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:47:41.621+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:47:41.624+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:47:41.623+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:47:41.692+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:47:41.689+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 11, in <module>
    import create_tables
ModuleNotFoundError: No module named 'create_tables'
[2023-12-10T18:47:41.693+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:47:41.718+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.104 seconds
[2023-12-10T18:47:58.887+0000] {processor.py:157} INFO - Started process (PID=148) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:47:58.890+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:47:58.895+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:47:58.894+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:47:58.947+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:47:58.942+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 8, in <module>
    sys.path.insert(path)
TypeError: insert expected 2 arguments, got 1
[2023-12-10T18:47:58.951+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:47:58.983+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.105 seconds
[2023-12-10T18:48:16.112+0000] {processor.py:157} INFO - Started process (PID=149) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:48:16.119+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:48:16.122+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:48:16.122+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:48:16.185+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:48:16.182+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 7
    path = '/Users/mady/Desktop/Data:/Users/mady/Desktop/Data Engineering/Projects/data_eng_project_1/airflow_project_1/data"
                                                                                                                            ^
SyntaxError: EOL while scanning string literal
[2023-12-10T18:48:16.187+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:48:16.217+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.111 seconds
[2023-12-10T18:48:19.157+0000] {processor.py:157} INFO - Started process (PID=150) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:48:19.159+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:48:19.162+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:48:19.162+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:48:19.175+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:48:19.174+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 8, in <module>
    sys.path.insert(path)
TypeError: insert expected 2 arguments, got 1
[2023-12-10T18:48:19.176+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:48:19.204+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.052 seconds
[2023-12-10T18:48:23.238+0000] {processor.py:157} INFO - Started process (PID=158) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:48:23.240+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:48:23.244+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:48:23.243+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:48:23.263+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:48:23.261+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 11, in <module>
    import create_tables
ModuleNotFoundError: No module named 'create_tables'
[2023-12-10T18:48:23.265+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:48:23.298+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.066 seconds
[2023-12-10T18:48:53.549+0000] {processor.py:157} INFO - Started process (PID=167) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:48:53.551+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:48:53.554+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:48:53.553+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:48:53.638+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:48:53.636+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 11, in <module>
    import create_tables
ModuleNotFoundError: No module named 'create_tables'
[2023-12-10T18:48:53.658+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:48:53.706+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.160 seconds
[2023-12-10T18:49:23.886+0000] {processor.py:157} INFO - Started process (PID=175) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:49:23.889+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:49:23.894+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:49:23.893+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:49:23.908+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:49:23.905+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 11, in <module>
    import create_tables
ModuleNotFoundError: No module named 'create_tables'
[2023-12-10T18:49:23.909+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:49:23.936+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.061 seconds
[2023-12-10T18:49:54.181+0000] {processor.py:157} INFO - Started process (PID=182) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:49:54.183+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:49:54.186+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:49:54.185+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:49:54.194+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:49:54.192+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 11, in <module>
    import create_tables
ModuleNotFoundError: No module named 'create_tables'
[2023-12-10T18:49:54.195+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:49:54.218+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.041 seconds
[2023-12-10T18:50:24.511+0000] {processor.py:157} INFO - Started process (PID=190) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:50:24.512+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:50:24.514+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:50:24.514+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:50:24.522+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:50:24.521+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 11, in <module>
    import create_tables
ModuleNotFoundError: No module named 'create_tables'
[2023-12-10T18:50:24.523+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:50:24.544+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.036 seconds
[2023-12-10T18:50:54.845+0000] {processor.py:157} INFO - Started process (PID=198) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:50:54.846+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:50:54.850+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:50:54.849+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:50:54.859+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:50:54.857+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 11, in <module>
    import create_tables
ModuleNotFoundError: No module named 'create_tables'
[2023-12-10T18:50:54.860+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:50:54.880+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.041 seconds
[2023-12-10T18:51:25.077+0000] {processor.py:157} INFO - Started process (PID=206) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:51:25.078+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:51:25.081+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:51:25.081+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:51:25.092+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:51:25.090+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 11, in <module>
    import create_tables
ModuleNotFoundError: No module named 'create_tables'
[2023-12-10T18:51:25.093+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:51:25.114+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.042 seconds
[2023-12-10T18:51:55.405+0000] {processor.py:157} INFO - Started process (PID=214) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:51:55.407+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:51:55.410+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:51:55.410+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:51:55.419+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:51:55.418+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 11, in <module>
    import create_tables
ModuleNotFoundError: No module named 'create_tables'
[2023-12-10T18:51:55.421+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:51:55.442+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.041 seconds
[2023-12-10T18:52:25.684+0000] {processor.py:157} INFO - Started process (PID=222) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:52:25.686+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:52:25.689+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:52:25.689+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:52:25.696+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:52:25.695+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 11, in <module>
    import create_tables
ModuleNotFoundError: No module named 'create_tables'
[2023-12-10T18:52:25.697+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:52:25.717+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.037 seconds
[2023-12-10T18:52:56.020+0000] {processor.py:157} INFO - Started process (PID=230) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:52:56.022+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:52:56.025+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:52:56.025+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:52:56.035+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:52:56.033+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 11, in <module>
    import create_tables
ModuleNotFoundError: No module named 'create_tables'
[2023-12-10T18:52:56.037+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:52:56.061+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.046 seconds
[2023-12-10T18:53:26.316+0000] {processor.py:157} INFO - Started process (PID=238) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:53:26.318+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:53:26.323+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:53:26.323+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:53:26.334+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:53:26.332+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 11, in <module>
    import create_tables
ModuleNotFoundError: No module named 'create_tables'
[2023-12-10T18:53:26.335+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:53:26.356+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.045 seconds
[2023-12-10T18:53:56.578+0000] {processor.py:157} INFO - Started process (PID=246) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:53:56.579+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:53:56.582+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:53:56.582+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:53:56.593+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:53:56.591+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 11, in <module>
    import create_tables
ModuleNotFoundError: No module named 'create_tables'
[2023-12-10T18:53:56.595+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:53:56.622+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.049 seconds
[2023-12-10T18:54:26.867+0000] {processor.py:157} INFO - Started process (PID=254) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:54:26.868+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:54:26.871+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:54:26.871+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:54:26.880+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:54:26.879+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 11, in <module>
    import create_tables
ModuleNotFoundError: No module named 'create_tables'
[2023-12-10T18:54:26.881+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:54:26.901+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.039 seconds
[2023-12-10T18:54:57.284+0000] {processor.py:157} INFO - Started process (PID=263) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:54:57.287+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:54:57.291+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:54:57.291+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:54:57.303+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:54:57.300+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 11, in <module>
    import create_tables
ModuleNotFoundError: No module named 'create_tables'
[2023-12-10T18:54:57.304+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:54:57.328+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.054 seconds
[2023-12-10T18:55:27.568+0000] {processor.py:157} INFO - Started process (PID=271) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:55:27.570+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:55:27.574+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:55:27.573+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:55:27.582+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:55:27.581+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 11, in <module>
    import create_tables
ModuleNotFoundError: No module named 'create_tables'
[2023-12-10T18:55:27.583+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:55:27.604+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.043 seconds
[2023-12-10T18:55:57.918+0000] {processor.py:157} INFO - Started process (PID=279) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:55:57.921+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:55:57.926+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:55:57.926+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:55:57.941+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:55:57.938+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 11, in <module>
    import create_tables
ModuleNotFoundError: No module named 'create_tables'
[2023-12-10T18:55:57.943+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:55:57.966+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.057 seconds
[2023-12-10T18:56:28.137+0000] {processor.py:157} INFO - Started process (PID=287) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:56:28.138+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:56:28.143+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:56:28.142+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:56:28.155+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:56:28.152+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 11, in <module>
    import create_tables
ModuleNotFoundError: No module named 'create_tables'
[2023-12-10T18:56:28.157+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:56:28.187+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.056 seconds
[2023-12-10T18:56:58.345+0000] {processor.py:157} INFO - Started process (PID=295) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:56:58.347+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:56:58.350+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:56:58.349+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:56:58.357+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:56:58.355+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 11, in <module>
    import create_tables
ModuleNotFoundError: No module named 'create_tables'
[2023-12-10T18:56:58.358+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:56:58.381+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.040 seconds
[2023-12-10T18:57:28.536+0000] {processor.py:157} INFO - Started process (PID=303) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:57:28.538+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:57:28.542+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:57:28.541+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:57:28.554+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:57:28.552+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 11, in <module>
    import create_tables
ModuleNotFoundError: No module named 'create_tables'
[2023-12-10T18:57:28.556+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:57:28.589+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.059 seconds
[2023-12-10T18:57:58.780+0000] {processor.py:157} INFO - Started process (PID=311) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:57:58.781+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:57:58.784+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:57:58.784+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:57:58.794+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:57:58.792+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 11, in <module>
    import create_tables
ModuleNotFoundError: No module named 'create_tables'
[2023-12-10T18:57:58.795+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:57:58.822+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.046 seconds
[2023-12-10T18:58:28.974+0000] {processor.py:157} INFO - Started process (PID=319) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:58:28.975+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:58:28.979+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:58:28.979+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:58:28.991+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:58:28.989+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 11, in <module>
    import create_tables
ModuleNotFoundError: No module named 'create_tables'
[2023-12-10T18:58:28.993+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:58:29.017+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.049 seconds
[2023-12-10T18:58:59.191+0000] {processor.py:157} INFO - Started process (PID=327) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:58:59.193+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:58:59.197+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:58:59.196+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:58:59.204+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:58:59.203+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 11, in <module>
    import create_tables
ModuleNotFoundError: No module named 'create_tables'
[2023-12-10T18:58:59.205+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:58:59.232+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.046 seconds
[2023-12-10T18:59:29.467+0000] {processor.py:157} INFO - Started process (PID=335) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:59:29.468+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:59:29.471+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:59:29.471+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:59:29.481+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:59:29.479+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 11, in <module>
    import create_tables
ModuleNotFoundError: No module named 'create_tables'
[2023-12-10T18:59:29.483+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:59:29.512+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.050 seconds
[2023-12-10T18:59:59.757+0000] {processor.py:157} INFO - Started process (PID=344) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:59:59.758+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T18:59:59.761+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:59:59.760+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:59:59.768+0000] {logging_mixin.py:154} INFO - [2023-12-10T18:59:59.767+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 11, in <module>
    import create_tables
ModuleNotFoundError: No module named 'create_tables'
[2023-12-10T18:59:59.769+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T18:59:59.797+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.044 seconds
[2023-12-10T19:00:29.959+0000] {processor.py:157} INFO - Started process (PID=352) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T19:00:29.961+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T19:00:29.963+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:00:29.963+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T19:00:29.971+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:00:29.969+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 11, in <module>
    import create_tables
ModuleNotFoundError: No module named 'create_tables'
[2023-12-10T19:00:29.972+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T19:00:30.003+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.047 seconds
[2023-12-10T19:01:00.196+0000] {processor.py:157} INFO - Started process (PID=360) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T19:01:00.198+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T19:01:00.202+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:01:00.202+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T19:01:00.213+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:01:00.210+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 11, in <module>
    import create_tables
ModuleNotFoundError: No module named 'create_tables'
[2023-12-10T19:01:00.214+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T19:01:00.249+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.058 seconds
[2023-12-10T19:01:30.468+0000] {processor.py:157} INFO - Started process (PID=369) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T19:01:30.470+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T19:01:30.474+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:01:30.474+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T19:01:30.498+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:01:30.495+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 11, in <module>
    import create_tables
ModuleNotFoundError: No module named 'create_tables'
[2023-12-10T19:01:30.500+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T19:01:30.538+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.075 seconds
[2023-12-10T19:02:00.754+0000] {processor.py:157} INFO - Started process (PID=377) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T19:02:00.756+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T19:02:00.759+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:02:00.758+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T19:02:00.768+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:02:00.766+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 11, in <module>
    import create_tables
ModuleNotFoundError: No module named 'create_tables'
[2023-12-10T19:02:00.769+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T19:02:00.801+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.051 seconds
[2023-12-10T19:22:12.817+0000] {processor.py:157} INFO - Started process (PID=390) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T19:22:12.837+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T19:22:12.912+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:22:12.910+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T19:22:12.973+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:22:12.965+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 11, in <module>
    import create_tables
ModuleNotFoundError: No module named 'create_tables'
[2023-12-10T19:22:12.975+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T19:22:13.048+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.304 seconds
[2023-12-10T19:23:50.764+0000] {processor.py:157} INFO - Started process (PID=392) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T19:23:50.768+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T19:23:50.829+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:23:50.828+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T19:23:50.910+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:23:50.883+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 11, in <module>
    import create_tables
ModuleNotFoundError: No module named 'create_tables'
[2023-12-10T19:23:50.953+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T19:23:51.034+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.303 seconds
[2023-12-10T19:24:21.378+0000] {processor.py:157} INFO - Started process (PID=407) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T19:24:21.381+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T19:24:21.387+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:24:21.387+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T19:24:21.402+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:24:21.398+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 11, in <module>
    import create_tables
ModuleNotFoundError: No module named 'create_tables'
[2023-12-10T19:24:21.403+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T19:24:21.459+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.088 seconds
[2023-12-10T19:24:51.650+0000] {processor.py:157} INFO - Started process (PID=415) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T19:24:51.652+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T19:24:51.654+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:24:51.654+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T19:24:51.662+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:24:51.661+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 11, in <module>
    import create_tables
ModuleNotFoundError: No module named 'create_tables'
[2023-12-10T19:24:51.664+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T19:24:51.686+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.041 seconds
[2023-12-10T19:25:21.912+0000] {processor.py:157} INFO - Started process (PID=423) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T19:25:21.913+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T19:25:21.916+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:25:21.916+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T19:25:21.927+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:25:21.924+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 11, in <module>
    import create_tables
ModuleNotFoundError: No module named 'create_tables'
[2023-12-10T19:25:21.928+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T19:25:21.954+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.046 seconds
[2023-12-10T19:25:52.161+0000] {processor.py:157} INFO - Started process (PID=431) to work on /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T19:25:52.163+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/main_de_project_1_dag.py for tasks to queue
[2023-12-10T19:25:52.166+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:25:52.166+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T19:25:52.177+0000] {logging_mixin.py:154} INFO - [2023-12-10T19:25:52.175+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/main_de_project_1_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main_de_project_1_dag.py", line 11, in <module>
    import create_tables
ModuleNotFoundError: No module named 'create_tables'
[2023-12-10T19:25:52.178+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/main_de_project_1_dag.py
[2023-12-10T19:25:52.200+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/main_de_project_1_dag.py took 0.043 seconds
